DataFrame students
+-------------+--------+
| Column Name | Type   |
+-------------+--------+
| id          | int    |
| first       | object |
| last        | object |
| age         | int    |
+-------------+--------+
Write a solution to rename the columns as follows:

id to student_id
first to first_name
last to last_name
age to age_in_years
The result format is in the following example.

 

Example 1:
Input:
+----+---------+----------+-----+
| id | first   | last     | age |
+----+---------+----------+-----+
| 1  | Mason   | King     | 6   |
| 2  | Ava     | Wright   | 7   |
| 3  | Taylor  | Hall     | 16  |
| 4  | Georgia | Thompson | 18  |
| 5  | Thomas  | Moore    | 10  |
+----+---------+----------+-----+
Output:
+------------+------------+-----------+--------------+
| student_id | first_name | last_name | age_in_years |
+------------+------------+-----------+--------------+
| 1          | Mason      | King      | 6            |
| 2          | Ava        | Wright    | 7            |
| 3          | Taylor     | Hall      | 16           |
| 4          | Georgia    | Thompson  | 18           |
| 5          | Thomas     | Moore     | 10           |
+------------+------------+-----------+--------------+
Explanation: 
The column names are changed accordingly.

In [3]:
import pandas as pd

# Input DataFrame
students = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "first": ["Mason", "Ava", "Taylor", "Georgia", "Thomas"],
    "last": ["King", "Wright", "Hall", "Thompson", "Moore"],
    "age": [6, 7, 16, 18, 10]
})
students

   id    first      last  age
0   1    Mason      King    6
1   2      Ava    Wright    7
2   3   Taylor      Hall   16
3   4  Georgia  Thompson   18
4   5   Thomas     Moore   10

In [5]:

# Function
def renameColumns(students: pd.DataFrame) -> pd.DataFrame:
    students.columns = ["student_id", "first_name", "last_name", "age_in_years"]
    return students

# Apply function
renameColumns(students)

   student_id first_name last_name  age_in_years
0           1      Mason      King             6
1           2        Ava    Wright             7
2           3     Taylor      Hall            16
3           4    Georgia  Thompson            18
4           5     Thomas     Moore            10

## OR

In [4]:
def renameColumns(students: pd.DataFrame) -> pd.DataFrame:
    return students.rename(columns={
        "id": "student_id",
        "first": "first_name",
        "last": "last_name",
        "age": "age_in_years"
    })
renameColumns(students)

   student_id first_name last_name  age_in_years
0           1      Mason      King             6
1           2        Ava    Wright             7
2           3     Taylor      Hall            16
3           4    Georgia  Thompson            18
4           5     Thomas     Moore            10