Write a solution to create a DataFrame from a 2D list called student_data. This 2D list contains the IDs and ages of some students. 

The DataFrame should have two columns, student_id and age, and be in the same order as the original 2D list. 

The result format is in the following example. 

Example 1:

Input:
student_data:
[
  [1, 15],
  [2, 11],
  [3, 11],
  [4, 20]
]
Output:
+------------+-----+
| student_id | age |
+------------+-----+
| 1          | 15  |
| 2          | 11  |
| 3          | 11  |
| 4          | 20  |
+------------+-----+
Explanation:
A DataFrame was created on top of student_data, with two columns named student_id and age.

## SOLUTION

In [6]:
import pandas as pd
from typing import List
def createDataframe(student_data: List[List[int]]) -> pd.DataFrame:
    return pd.DataFrame(student_data, columns=["student_id", "age"])

In [9]:
# 1D lists: student_id & age and convert it into 2D List by using zip function 

student_id = [1,2,3,4]
age = [15,11,11,20]

student_data = list(zip(student_id, age))
student_data

[(1, 15), (2, 11), (3, 11), (4, 20)]

In [7]:
# OR
# 2D List 
student_data = [ [1,15], [2,11], [3,11], [4,15] ]

In [10]:
df = createDataframe(student_data)
df

   student_id  age
0           1   15
1           2   11
2           3   11
3           4   20

## ANOTHER SOLUTION

In [16]:
import pandas as pd

def createDataframe(student_data: List[List[int]]) -> pd.DataFrame:
    column_names = ["student_id", "age"]
    result_dataframe = pd.DataFrame(student_data, columns=column_names)
    return result_dataframe

In [19]:
student_data = [ [1,15], [2,11], [3,11], [4,15] ]
df = createDataframe(student_data)
df

   student_id  age
0           1   15
1           2   11
2           3   11
3           4   15

## ANOTHER SOLUTION

In [4]:
import pandas as pd
from typing import List

In [5]:
def createDataframe(student_data: List[List[int]]) -> pd.DataFrame:
    return pd.DataFrame(student_data, columns=["student_id", "age"])

In [6]:
student_data = [ [1,15], [2,11], [3,11], [4,15] ]

In [7]:
createDataframe(student_data)

   student_id  age
0           1   15
1           2   11
2           3   11
3           4   15