DataFrame weather
+-------------+--------+
| Column Name | Type   |
+-------------+--------+
| city        | object |
| month       | object |
| temperature | int    |
+-------------+--------+
Write a solution to pivot the data so that each row represents temperatures for a specific month, and each city is a separate column.

The result format is in the following example.

 

Example 1:
Input:
+--------------+----------+-------------+
| city         | month    | temperature |
+--------------+----------+-------------+
| Jacksonville | January  | 13          |
| Jacksonville | February | 23          |
| Jacksonville | March    | 38          |
| Jacksonville | April    | 5           |
| Jacksonville | May      | 34          |
| ElPaso       | January  | 20          |
| ElPaso       | February | 6           |
| ElPaso       | March    | 26          |
| ElPaso       | April    | 2           |
| ElPaso       | May      | 43          |
+--------------+----------+-------------+
Output:
+----------+--------+--------------+
| month    | ElPaso | Jacksonville |
+----------+--------+--------------+
| April    | 2      | 5            |
| February | 6      | 23           |
| January  | 20     | 13           |
| March    | 26     | 38           |
| May      | 43     | 34           |
+----------+--------+--------------+
Explanation:
The table is pivoted, each column represents a city, and each row represents a specific month.

In [16]:
import pandas as pd

data = {
    "city": [
        "Jacksonville", "Jacksonville", "Jacksonville", "Jacksonville", "Jacksonville",
        "ElPaso", "ElPaso", "ElPaso", "ElPaso", "ElPaso"
    ],
    "month": [
        "January", "February", "March", "April", "May",
        "January", "February", "March", "April", "May"
    ],
    "temperature": [13, 23, 38, 5, 34, 20, 6, 26, 2, 43]
}

weather = pd.DataFrame(data)
weather

           city     month  temperature
0  Jacksonville   January           13
1  Jacksonville  February           23
2  Jacksonville     March           38
3  Jacksonville     April            5
4  Jacksonville       May           34
5        ElPaso   January           20
6        ElPaso  February            6
7        ElPaso     March           26
8        ElPaso     April            2
9        ElPaso       May           43

In [14]:
def pivotTable(weather: pd.DataFrame) -> pd.DataFrame:
    df = weather.pivot(index='month', columns='city', values='temperature')
    df = df.reset_index()          # bring month as column
    df.columns.name = None         # remove "city" label
    return df

In [15]:
pivotTable(weather)

      month  ElPaso  Jacksonville
0     April       2             5
1  February       6            23
2   January      20            13
3     March      26            38
4       May      43            34

In [18]:
def pivotTable(weather: pd.DataFrame) -> pd.DataFrame:
    return weather.pivot(index='month', columns='city', values='temperature') \
                  .rename_axis(None, axis=1) \
                  .reset_index()

In [20]:

pivotTable(weather)

      month  ElPaso  Jacksonville
0     April       2             5
1  February       6            23
2   January      20            13
3     March      26            38
4       May      43            34

In [21]:
weather

           city     month  temperature
0  Jacksonville   January           13
1  Jacksonville  February           23
2  Jacksonville     March           38
3  Jacksonville     April            5
4  Jacksonville       May           34
5        ElPaso   January           20
6        ElPaso  February            6
7        ElPaso     March           26
8        ElPaso     April            2
9        ElPaso       May           43