DataFrame employees
+-------------+--------+
| Column Name | Type   |
+-------------+--------+
| name        | object |
| salary      | int    |
+-------------+--------+
A company intends to give its employees a pay rise.

Write a solution to modify the salary column by multiplying each salary by 2.

The result format is in the following example.

 

Example 1:

Input:
DataFrame employees
+---------+--------+
| name    | salary |
+---------+--------+
| Jack    | 19666  |
| Piper   | 74754  |
| Mia     | 62509  |
| Ulysses | 54866  |
+---------+--------+
Output:
+---------+--------+
| name    | salary |
+---------+--------+
| Jack    | 39332  |
| Piper   | 149508 |
| Mia     | 125018 |
| Ulysses | 109732 |
+---------+--------+
Explanation:
Every salary has been doubled.

## SOLUTION 1

In [1]:
import pandas as pd

def modifySalaryColumn(employees: pd.DataFrame) -> pd.DataFrame:
    return employees.assign(salary=employees['salary'] * 2)

In [2]:
# Create the DataFrame
data = {
    "name": ["Jack", "Piper", "Mia", "Ulysses"],
    "salary": [19666, 74754, 62509, 54866]
}

employees = pd.DataFrame(data)

print(employees)

      name  salary
0     Jack   19666
1    Piper   74754
2      Mia   62509
3  Ulysses   54866

In [3]:
modifySalaryColumn(employees)

      name  salary
0     Jack   39332
1    Piper  149508
2      Mia  125018
3  Ulysses  109732

## SOLUTION 2

In [4]:
import pandas as pd

def modifySalaryColumn(employees: pd.DataFrame) -> pd.DataFrame:
    employees['salary'] = employees['salary'] * 2
    return employees

In [5]:
# Create the DataFrame
employees = pd.DataFrame(
    {
    "name": ["Jack", "Piper", "Mia", "Ulysses"],
    "salary": [19666, 74754, 62509, 54866]
}
)

employees

      name  salary
0     Jack   19666
1    Piper   74754
2      Mia   62509
3  Ulysses   54866

In [6]:
modifySalaryColumn(employees)

      name  salary
0     Jack   39332
1    Piper  149508
2      Mia  125018
3  Ulysses  109732