DataFrame report
+-------------+--------+
| Column Name | Type   |
+-------------+--------+
| product     | object |
| quarter_1   | int    |
| quarter_2   | int    |
| quarter_3   | int    |
| quarter_4   | int    |
+-------------+--------+
Write a solution to reshape the data so that each row represents sales data for a product in a specific quarter.

The result format is in the following example.

 

Example 1:

Input:
+-------------+-----------+-----------+-----------+-----------+
| product     | quarter_1 | quarter_2 | quarter_3 | quarter_4 |
+-------------+-----------+-----------+-----------+-----------+
| Umbrella    | 417       | 224       | 379       | 611       |
| SleepingBag | 800       | 936       | 93        | 875       |
+-------------+-----------+-----------+-----------+-----------+
Output:
+-------------+-----------+-------+
| product     | quarter   | sales |
+-------------+-----------+-------+
| Umbrella    | quarter_1 | 417   |
| SleepingBag | quarter_1 | 800   |
| Umbrella    | quarter_2 | 224   |
| SleepingBag | quarter_2 | 936   |
| Umbrella    | quarter_3 | 379   |
| SleepingBag | quarter_3 | 93    |
| Umbrella    | quarter_4 | 611   |
| SleepingBag | quarter_4 | 875   |
+-------------+-----------+-------+
Explanation:
The DataFrame is reshaped from wide to long format. Each row represents the sales of a product in a quarter.

In [4]:
import pandas as pd

report = pd.DataFrame(
    {
    "product": ["Umbrella", "SleepingBag"],
    "quarter_1": [417, 800],
    "quarter_2": [224, 936],
    "quarter_3": [379, 93],
    "quarter_4": [611, 875]
}
)
report

       product  quarter_1  quarter_2  quarter_3  quarter_4
0     Umbrella        417        224        379        611
1  SleepingBag        800        936         93        875

In [2]:
def meltTable(report: pd.DataFrame) -> pd.DataFrame:
    report = report.melt(
        id_vars=["product"],
        value_vars=["quarter_1", "quarter_2", "quarter_3", "quarter_4"],
        var_name="quarter",
        value_name="sales",
    )
    return report

In [3]:
meltTable(report)

       product    quarter  sales
0     Umbrella  quarter_1    417
1  SleepingBag  quarter_1    800
2     Umbrella  quarter_2    224
3  SleepingBag  quarter_2    936
4     Umbrella  quarter_3    379
5  SleepingBag  quarter_3     93
6     Umbrella  quarter_4    611
7  SleepingBag  quarter_4    875

In [5]:
report

       product  quarter_1  quarter_2  quarter_3  quarter_4
0     Umbrella        417        224        379        611
1  SleepingBag        800        936         93        875

In [8]:
def meltTable(report: pd.DataFrame) -> pd.DataFrame:
    return report.melt(
        id_vars=["product"],
        value_vars=["quarter_1", "quarter_2", "quarter_3", "quarter_4"],
        var_name="quarter",
        value_name="sales",
    )

In [9]:
meltTable(report)

       product    quarter  sales
0     Umbrella  quarter_1    417
1  SleepingBag  quarter_1    800
2     Umbrella  quarter_2    224
3  SleepingBag  quarter_2    936
4     Umbrella  quarter_3    379
5  SleepingBag  quarter_3     93
6     Umbrella  quarter_4    611
7  SleepingBag  quarter_4    875