DataFrame products
+-------------+--------+
| Column Name | Type   |
+-------------+--------+
| name        | object |
| quantity    | int    |
| price       | int    |
+-------------+--------+
Write a solution to fill in the missing value as 0 in the quantity column.

The result format is in the following example.

 

Example 1:
Input:+-----------------+----------+-------+
| name            | quantity | price |
+-----------------+----------+-------+
| Wristwatch      | None     | 135   |
| WirelessEarbuds | None     | 821   |
| GolfClubs       | 779      | 9319  |
| Printer         | 849      | 3051  |
+-----------------+----------+-------+
Output:
+-----------------+----------+-------+
| name            | quantity | price |
+-----------------+----------+-------+
| Wristwatch      | 0        | 135   |
| WirelessEarbuds | 0        | 821   |
| GolfClubs       | 779      | 9319  |
| Printer         | 849      | 3051  |
+-----------------+----------+-------+
Explanation: 
The quantity for Wristwatch and WirelessEarbuds are filled by 0.

In [5]:
import pandas as pd

data = {
    "name": ["Wristwatch", "WirelessEarbuds", "GolfClubs", "Printer"],
    "quantity": [None, None, 779, 849],
    "price": [135, 821, 9319, 3051]
}

products = pd.DataFrame(data)

products

              name  quantity  price
0       Wristwatch       NaN    135
1  WirelessEarbuds       NaN    821
2        GolfClubs     779.0   9319
3          Printer     849.0   3051

In [3]:
def fillMissingValues(products: pd.DataFrame) -> pd.DataFrame:
    products["quantity"] = products["quantity"].fillna(0)
    return products

In [4]:
fillMissingValues(products)

              name  quantity  price
0       Wristwatch       0.0    135
1  WirelessEarbuds       0.0    821
2        GolfClubs     779.0   9319
3          Printer     849.0   3051

## OR

In [6]:
products

              name  quantity  price
0       Wristwatch       NaN    135
1  WirelessEarbuds       NaN    821
2        GolfClubs     779.0   9319
3          Printer     849.0   3051

In [15]:
def fillMissingValues(products: pd.DataFrame) -> pd.DataFrame:
    products = products.fillna({"quantity": 0})
    return products

In [16]:
fillMissingValues(products)

              name  quantity  price
0       Wristwatch       0.0    135
1  WirelessEarbuds       0.0    821
2        GolfClubs     779.0   9319
3          Printer     849.0   3051