DataFrame students
+-------------+--------+
| Column Name | Type   |
+-------------+--------+
| student_id  | int    |
| name        | object |
| age         | int    |
| grade       | float  |
+-------------+--------+
Write a solution to correct the errors:

The grade column is stored as floats, convert it to integers.

The result format is in the following example.

 

Example 1:
Input:
DataFrame students:
+------------+------+-----+-------+
| student_id | name | age | grade |
+------------+------+-----+-------+
| 1          | Ava  | 6   | 73.0  |
| 2          | Kate | 15  | 87.0  |
+------------+------+-----+-------+
Output:
+------------+------+-----+-------+
| student_id | name | age | grade |
+------------+------+-----+-------+
| 1          | Ava  | 6   | 73    |
| 2          | Kate | 15  | 87    |
+------------+------+-----+-------+
Explanation: 
The data types of the column grade is converted to int.

In [11]:
import pandas as pd

def changeDatatype(students: pd.DataFrame) -> pd.DataFrame:
    return students.astype({'grade': 'int'})

In [23]:
students = pd.DataFrame(
    {
    "student_id": [1, 2],
    "name": ["Ava", "Kate"],
    "age": [6, 15],
    "grade": [73.0, 87.0]
}
)

In [13]:
students.dtypes

student_id      int64
name           object
age             int64
grade         float64
dtype: object

In [14]:
students1 = changeDatatype(students)
changeDatatype(students1)

   student_id  name  age  grade
0           1   Ava    6     73
1           2  Kate   15     87

In [15]:
students1.dtypes

student_id     int64
name          object
age            int64
grade          int64
dtype: object

## OR

In [18]:
def changeDatatype(students: pd.DataFrame) -> pd.DataFrame:
    students["grade"] = students["grade"].astype(int)
    return students

In [19]:
students.dtypes

student_id      int64
name           object
age             int64
grade         float64
dtype: object

In [20]:
students1 = changeDatatype(students)
changeDatatype(students1)

   student_id  name  age  grade
0           1   Ava    6     73
1           2  Kate   15     87

In [21]:
students1.dtypes

student_id     int64
name          object
age            int64
grade          int64
dtype: object

## OR

In [25]:
def changeDatatype(students: pd.DataFrame) -> pd.DataFrame:
    students["grade"] = students["grade"].map(int)
    return students

In [26]:
students.dtypes

student_id      int64
name           object
age             int64
grade         float64
dtype: object

In [27]:
students1 = changeDatatype(students)
changeDatatype(students)

   student_id  name  age  grade
0           1   Ava    6     73
1           2  Kate   15     87

In [28]:
students1.dtypes

student_id     int64
name          object
age            int64
grade          int64
dtype: object